version: '3.8'

services:
  # Configuration commune (pour éviter les répétitions)
  base-robot: &base-robot
    build: .
    network_mode: "host"
    environment:
      - ROBOT_IP=${ROBOT_IP}

  # Script 1 : Test de connexion (Popup)
  test-connexion:
    <<: *base-robot
    command: python Connection_Test.py

  # Script 2 : Contrôle clavier (Le plus complexe)
  keyboard:
    <<: *base-robot
    command: python keyboard_control.py
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  # Script 3 : Lecture des joints
  reading:
    <<: *base-robot
    command: python Test_rtde_read.py